### ISSUE TITLE
Mac OS "Quick Start" instructions are untested

### ISSUE THREAD

**Issue by gregkrsak** [gregkrsak/first_nes#22]

**Comment by elennick** [comment]
@gregkrsak I just tested your instructions and they worked pretty much perfectly out of the box... i already had `brew` and `make` installed so i didn't have to do that part but everything else worked. I wrote down my steps as I did them but they are pretty much identical to what you have in your readme:

* `brew install cc65`
* install nestopia from http://www.bannister.org/cgi-bin/download.cgi?nestopia
* git clone https://github.com/gregkrsak/first_nes
* cd first_nes
* make
* start nestopia and load “first_nes.nes"

After that it loads up the nes ROM and you can move Luigi back and forth with Shift and Opt.

**Comment by gregkrsak** [comment]
Thanks Evan! I really appreciate it!
